### ISSUE TITLE
Size of vector3 is 16 bytes

### ISSUE THREAD

**Issue by ghost** [kooparse/zalgebra#49]
title. using @sizeOf(Vec3) reveals that vector3 is 16 bytes big, instead of 12 bytes.

**Comment by glyh** [comment]
This is due to the underlying infrastructure. Vec3 is implemented with zig's native Vector type, which is designed to utilize SIMD. As a result, they align them up to multiples of 4(or $2^x$ for some x if I'm wrong).

So as long as we're using native vector type this has to be the case.

I kinda doubt why would you want to query @sizeof though.
