### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by jojolepro** [kooparse/zalgebra#5]
Hello!

Just wanted to let you know that usually function names are camelCase and types are PascalCase.
For example, const quat_f32 = Quaternion(f32); would be const QuatF32 = Quaternion(f32);

Source: https://ziglang.org/documentation/master/#Names

Continue your great work! :hearts:

**Comment by kooparse** [comment]
Yup, you're totally right. I started the project without knowing those rules (or there was still some debate around the Zig naming convention). I will definitely fix that very soon!

Also, I would love to change the API a bit, and adding the possibility of doing things like `Vec3(3, 4, 5)` instead of `Vec3.new(2, 3, 5)`; I'll probably do it while changing the naming convention. 

Thanks! :-)

**Comment by jojolepro** [comment]
I'm not too sure about the Vec3(x, y, z) syntax. I fear it will make it harder to have a Vec3 type to pass around since the name would clash with the constructor.
```c
pub fn Vec3(x: i32, y: i32, z: i32) <what here?> {
    return <what here?>.new(x, y, z);
}
```

**Comment by kooparse** [comment]
Yes but it's already the case with the "new" naming convention: `const vec3 = Vec3(f32)` => `const Vec3 = Vec3(f32)`. I don't want to rename it to `Vec3F32`, because f32 will be largely used.

The function `Vec3` should be renamed instead. But still, I'm not so sure too, I need to think about it  ;)

**Comment by kooparse** [comment]
Done! 

So all the functions are updated (`fromSlice`, `toRadians`, etc...). Types are now `Vec2`/`Mat4`. For variants I preferred `Vec2_f64` instead of `Vec2F64` but it could change in the future, we'll see!

**Comment by jojolepro** [comment]
Perfect, nicely done! :hearts:
